server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1
data:
  db:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test
  redis:
    addr: 127.0.0.1:6379
    auth: false
    user: user
    passwd: passwd
    db: 0
    read_timeout: 0.2
    write_timeout: 0.2
